"""Add rating, price, level, and age_group to tables

Revision ID: 48e591a76063
Revises: 4d3b23f9f78e
Create Date: 2023-03-29 08:40:37.155420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e591a76063'
down_revision = '4d3b23f9f78e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('level', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('age_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'age_group')
    op.drop_column('lessons', 'level')
    op.drop_column('instructors', 'price')
    op.drop_column('instructors', 'rating')
    # ### end Alembic commands ###
