"""First migration

Revision ID: 4d3b23f9f78e
Revises: 
Create Date: 2023-03-28 13:06:22.478412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3b23f9f78e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dancers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dancers_name'), 'dancers', ['name'], unique=False)
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructors_name'), 'instructors', ['name'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('dancer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dancer_id'], ['dancers.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_style'), 'lessons', ['style'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_style'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_instructors_name'), table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_dancers_name'), table_name='dancers')
    op.drop_table('dancers')
    # ### end Alembic commands ###
