"""fixed instructor class id

Revision ID: cb055c847dbe
Revises: 463ef599e342
Create Date: 2023-03-28 11:29:14.622956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb055c847dbe'
down_revision = '463ef599e342'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('style', sa.String(), nullable=True))
    op.add_column('lessons', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('dancer_id', sa.Integer(), nullable=True))
    op.drop_index('ix_lessons_type', table_name='lessons')
    op.create_index(op.f('ix_lessons_style'), 'lessons', ['style'], unique=False)
    op.create_foreign_key(None, 'lessons', 'instructors', ['instructor_id'], ['id'])
    op.create_foreign_key(None, 'lessons', 'dancers', ['dancer_id'], ['id'])
    op.drop_column('lessons', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_style'), table_name='lessons')
    op.create_index('ix_lessons_type', 'lessons', ['type'], unique=False)
    op.drop_column('lessons', 'dancer_id')
    op.drop_column('lessons', 'instructor_id')
    op.drop_column('lessons', 'style')
    # ### end Alembic commands ###
